# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicWorkerStub(object):
    """Music generation worker service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTheory = channel.unary_unary(
                '/musicforge.worker.MusicWorker/GenerateTheory',
                request_serializer=worker__pb2.TheoryRequest.SerializeToString,
                response_deserializer=worker__pb2.TheoryResponse.FromString,
                _registered_method=True)
        self.SynthesizeAudio = channel.unary_stream(
                '/musicforge.worker.MusicWorker/SynthesizeAudio',
                request_serializer=worker__pb2.AudioRequest.SerializeToString,
                response_deserializer=worker__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.SynthesizeVocals = channel.unary_stream(
                '/musicforge.worker.MusicWorker/SynthesizeVocals',
                request_serializer=worker__pb2.VocalRequest.SerializeToString,
                response_deserializer=worker__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.SeparateStems = channel.unary_unary(
                '/musicforge.worker.MusicWorker/SeparateStems',
                request_serializer=worker__pb2.StemRequest.SerializeToString,
                response_deserializer=worker__pb2.StemResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/musicforge.worker.MusicWorker/HealthCheck',
                request_serializer=worker__pb2.Empty.SerializeToString,
                response_deserializer=worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class MusicWorkerServicer(object):
    """Music generation worker service
    """

    def GenerateTheory(self, request, context):
        """Generate music theory elements (chords, structure, MIDI)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeAudio(self, request, context):
        """Synthesize instrumental audio with streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeVocals(self, request, context):
        """Synthesize vocal audio with streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeparateStems(self, request, context):
        """Separate audio into stems (drums, bass, vocals, other)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Check worker health and GPU status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateTheory': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTheory,
                    request_deserializer=worker__pb2.TheoryRequest.FromString,
                    response_serializer=worker__pb2.TheoryResponse.SerializeToString,
            ),
            'SynthesizeAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeAudio,
                    request_deserializer=worker__pb2.AudioRequest.FromString,
                    response_serializer=worker__pb2.AudioChunk.SerializeToString,
            ),
            'SynthesizeVocals': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeVocals,
                    request_deserializer=worker__pb2.VocalRequest.FromString,
                    response_serializer=worker__pb2.AudioChunk.SerializeToString,
            ),
            'SeparateStems': grpc.unary_unary_rpc_method_handler(
                    servicer.SeparateStems,
                    request_deserializer=worker__pb2.StemRequest.FromString,
                    response_serializer=worker__pb2.StemResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=worker__pb2.Empty.FromString,
                    response_serializer=worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'musicforge.worker.MusicWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('musicforge.worker.MusicWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicWorker(object):
    """Music generation worker service
    """

    @staticmethod
    def GenerateTheory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicforge.worker.MusicWorker/GenerateTheory',
            worker__pb2.TheoryRequest.SerializeToString,
            worker__pb2.TheoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/musicforge.worker.MusicWorker/SynthesizeAudio',
            worker__pb2.AudioRequest.SerializeToString,
            worker__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeVocals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/musicforge.worker.MusicWorker/SynthesizeVocals',
            worker__pb2.VocalRequest.SerializeToString,
            worker__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeparateStems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicforge.worker.MusicWorker/SeparateStems',
            worker__pb2.StemRequest.SerializeToString,
            worker__pb2.StemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicforge.worker.MusicWorker/HealthCheck',
            worker__pb2.Empty.SerializeToString,
            worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
